name: Test

on:
  release:
    types: [prereleased]

jobs:
  build:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}